### PR TITLE
Use struct to access (EEprom) configuration, this make the code more readable

### PR DESCRIPTION
**Pull request by cookieBerlin**
- Program memory usages changes from 27724 Bytes to 27146 Bytes

### CODE REVIEW

**Comment by amunters** [comment]
Hi Angelo,
Thanks for sharing this idea. Yes, using struct we can free a few hundred bytes which we can use for other more useful purposes!
I quickly tried your updated sketch but at startup the values are not (or not correctly) read from EEPROM (it appears that most of them are zero).
I haven't done any troubleshooting or debugging yet, this was just my first observation. Perhaps you can look into this.
Thanks, 73 Allard PE1NWL

**Comment by pavelmc** [comment]
Been there do that, @amunters you can look into my folk in pavelmc/bix40 here on github, I have done it and works like a charm.

73 de Pavel CO7WT.

**Comment by amunters** [comment]
Hi Angelo,
OK, I found the bug: In your code the readConfig() and saveConfig() routines were interchanged.
Everything works as expected after I switched them back.

**Comment by amunters** [comment]
There are still issues with the variable semiQSK. It always remains ON (true). The value for config.semiQSK also seems to interfere with the value of config.TUNING_RANGE.
Also config.VFOactive is not working correctly.
Perhaps the struct cannot handle booleans correctly?

**Comment by amunters** [comment]
This has meanwhile been implemented in v1.26

**Pull request closed without merging**
