### PR TITLE
Hack to enable Upper Sideband (USB)

### PR DESCRIPTION
**Pull request by shermozle**
Incorporate Andrew Beard's hack to enable upper sideband by having the tuning knob all the way to the right at switch on.

### CODE REVIEW

**Comment by amunters** [comment]
Hi Simon,
Thanks for this suggestion, I also tried Andrew's hack but on my radio it is not sufficient to only set variable isUSB to 1 to get USB working.
What happens is that by setting isUSB=1, the LO is set to the high side of the IF (about 19 MHz instead of about 5 MHz). The VFO signal gets attenuated too much at this higher frequency and the mixer does not get sufficient drive.
(note that I'm using the unmodified BITX40 board that still have C91 and C92 in place, some people removed them as these caps cause the attenuation at higher frequencies).

In order to compensate for this (without removing the caps) I had to increase the VFO drive level to 8mA in USB mode only:

si5351.drive_strength(SI5351_CLK2, SI5351_DRIVE_8MA);

The required drive strength may vary per radio. The default drive level is 2mA, what drive strength works best on your radio? Did you remove the two caps too?

Also in the default LSB mode it may be necessary to increase the drive strength. I found that by using 4mA instead of 2mA, the strong birdie at 7199 disappears. See message #24248 on the BITX20 iogroup. Do you get similar results?

I'm considering to combine Andrew's hack with the drive strength fix and set the correct drive strength depending on the mode.
73, Allard PE1NWL

**Comment by shermozle** [comment]
Hi there Allard.

I haven't made any hardware mods. In fact, I turned the BitX on for the first time today. I'm most interested in JT65 so USB is vital. With a temporary (and not very good) antenna I was able to copy and decode (through laptop microphone no less) a JT65 exchange, though the frequency seemed off from what was on the display.

I haven't played with the drive strength yet, but I've been following that thread. Hard to know what are birdies and what are the result of my very noisy RF environment.

I sent the pull request to you because yours seems to be the most active fork. There's a bunch of things I plan to play around with, including making more use of the screen itself (things like band limits), maybe a button to switch USB/LSB and getting enough control from a PC to do digital modes (PTT at minimum).

**Comment by amunters** [comment]
Simon, you mentioned that the frequency is off from what is on the display. Did you already do the calibration procedure? Please note that the current calibration routine assumes LSB mode.
When we add USB capability we must also rewrite the calibration routine so that it works in USB mode too.

**Comment by shermozle** [comment]
No I haven't done the calibration. Will give that a go but need to find a station to calibrate against. And for that matter wire up a function button I guess.

**Comment by amunters** [comment]
Simon, the latest release 1.07 provides the USB functionality you requested in a different way (via the Function Button). I therefore close your pull request.
73 Allard PE1NWL

**Pull request closed without merging**
