### PR TITLE
Optionally swap PTT_SENSE and SPOT for easier cabling.

### PR DESCRIPTION
**Pull request by SmittyHalibut**
This change allows P1 wiring to go entirely to the front panel, and P3 to go entirely to the RF board.  Without this, one wire on P1 goes to the RF board and one wire on P3 goes to the front panel. Both signals are digital, so PTT Sense going into A0 isn't necessary.

This patch is backwards compatible with the as-documented wiring, so should be safe to include.

### CODE REVIEW

**Comment by amunters** [comment]
Mark,
Thanks for your suggestion - Understand your point to have all wires from P1 go to the front panel, and wires from P3 to the main board. This would certainly make wiring easier.

However please note I'm currently working on a next release v1.21 which will have automatic keyer functionality.
For this we need yet another digital input. The "dit" contact will connect to the existing "KEY" input (A1), the "dah" contact will connect to pin D3.
D3 is on connector P3, so we will then have yet another wire from P3 going to the front panel.

Once the keyer functionality works well, I'm planning to start a new release cycle v2.xx which will have digital BFO. For this we will need some extra modification and wiring which will anyway not be downward compatible anymore to v1.xx
I believe v2 would be a good moment to rearrange the input/output pins for easier wiring as you suggested.
For now, as long as we are still in v1.xx, I'd like to keep the pin layout as is, so as to maintain downward compatibility.

73 Allard PE1NWL

**Comment by SmittyHalibut** [comment]
Certainly your decision either way. Note my patch uses a #define to enable or disable the switch, and it defaults to disable. Meaning, if you accept the pull request, it changes nothing. One would have to uncomment "//#define SMITTY_BUILD" to make any changes. 

Let me know if I can help with the code in any other way. I'm playing with DDS BFO for an IF Shift feature, and would be happy to submit code for that too if you're interested.

**Comment by SmittyHalibut** [comment]
Also, A6 is available for "dah". :-)

-Mark

**Comment by amunters** [comment]
No, on a Nano, pins A6 and A7 are analog inputs ONLY.
Not many programmers are aware of this, and so was I, so had to find this
out the hard way :=((

**Comment by SmittyHalibut** [comment]
Oh, interesting. I didn't know that. Fair enough. :-)

-Mark

**Comment by SmittyHalibut** [comment]
Err, that wasn't want I meant to do...  Stand by, let me remove that change from this pull-request.

**Pull request closed without merging**
